CREATE TABLE Employee (
	CPF NUMERIC(15) NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	EXTRA WORKED HOURS NUMERIC(18,2) NOT NULL,
	LAST TRAINING DATA DATE NOT NULL,
	PAYROLL TOTAL  NUMERIC(50)NOT NULL,
	CONSTRAINT employee_pk PRIMARY KEY (CPF)
);

CREATE TABLE Auditing (
	IDENTIFIER SERIAL NOT NULL,
	REGISTER_CODE NUMERIC(20) NOT NULL,
	DATETIME TIMESTAMP NOT NULL,
	CONSTRAINT auditing_pk PRIMARY KEY (IDENTIFIER),
	FOREIGN KEY (REGISTER_CPF) REFERENCES Employee (CPF)
);
